### ISSUE TITLE
It Wont Gen Friends

### ISSUE THREAD

**Issue by im-silent** [Hazza3100/ReplitGen#1]
So Heres The Situation Ok My Left Uncles Cousin Hates my mother ok but i have 0 friends so in oders ill need 1 to 3 big macs from taco bell

**Comment by Itamar1337** [comment]
I can be your friend as long as u pay 20$/hour

**Comment by im-silent** [comment]
im broke tho):

**Comment by Hazza3100** [comment]
I can make a friend generator, but you need to go outside first...

**Comment by im-silent** [comment]
oof ight one sec heading out side

**Comment by im-silent** [comment]
ight there i touched grass i jumped out my window luckily im on the first floor
